// Auto-generated by scripts/chgis/build_boundaries.py — do not edit manually
import type { ChgisSnapshot } from '@/lib/history/chgis/types';

import s_n0221 from './n0221.json';
import s_n0206 from './n0206.json';
import s_n0100 from './n0100.json';
import s_p0025 from './p0025.json';
import s_p0220 from './p0220.json';
import s_p0618 from './p0618.json';
import s_p0907 from './p0907.json';
import s_p0960 from './p0960.json';
import s_p1279 from './p1279.json';
import s_p1368 from './p1368.json';
import s_p1644 from './p1644.json';
import s_p1820 from './p1820.json';
import s_p1911 from './p1911.json';

export const chgisSnapshots: Record<number, ChgisSnapshot> = {
  [-221]: s_n0221 as ChgisSnapshot,
  [-206]: s_n0206 as ChgisSnapshot,
  [-100]: s_n0100 as ChgisSnapshot,
  25: s_p0025 as ChgisSnapshot,
  220: s_p0220 as ChgisSnapshot,
  618: s_p0618 as ChgisSnapshot,
  907: s_p0907 as ChgisSnapshot,
  960: s_p0960 as ChgisSnapshot,
  1279: s_p1279 as ChgisSnapshot,
  1368: s_p1368 as ChgisSnapshot,
  1644: s_p1644 as ChgisSnapshot,
  1820: s_p1820 as ChgisSnapshot,
  1911: s_p1911 as ChgisSnapshot,
};

export const chgisYears = [-221, -206, -100, 25, 220, 618, 907, 960, 1279, 1368, 1644, 1820, 1911] as const;
